version: '3'

services:
  lottery-nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - lottery-service

  lottery-mysql:
    image: mysql:latest
    volumes:
      - ./src/main/resources/sql/lottery.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  lottery-redis:
    image: redis

  lottery-service:
    image: lottery
    ports:
      - "8080:8080"
    depends_on:
      - lottery-mysql
      - lottery-redis